# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-07-27 15:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0003_vacancy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='duty',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='job_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
