# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-07-27 16:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0004_auto_20190727_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='initial_profession',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='vacancies_initial', to='hackathon.Profession'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vacancy',
            name='predicted_profession',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vacancies_predicted', to='hackathon.Profession'),
        ),
        migrations.AlterField(
            model_name='profession',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
