# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-07-27 23:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0006_auto_20190727_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='profession',
            name='category',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='profession',
            name='etks',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
