# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-07-27 23:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0007_auto_20190727_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profession',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
