# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-07-28 12:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0008_auto_20190727_2314'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassOkso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=512, null=True)),
                ('professions', models.ManyToManyField(blank=True, to='hackathon.Profession')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_code', models.CharField(blank=True, max_length=255, null=True)),
                ('region_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
