# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-07-27 18:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profinfoglobal',
            name='profession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hackathon.Profession'),
        ),
        migrations.AlterField(
            model_name='profinforegional',
            name='profession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hackathon.Profession'),
        ),
        migrations.DeleteModel(
            name='Profession',
        ),
    ]
